name = eye_spy
title = Eye Spy
description = Lets you see information about the node/entity/item you are looking at.
optional_depends = default, mcl_core, mcl_tools, mcl_doc
supported_games = minetest_game, mineclone2, mineclonia
min_minetest_version = 5.8.0
author = cjgray24
